"""Static lookups used by the app.

`DEVICES` maps an Amazon device type to a friendly model name and generation,
used only to pick the right SVG pairing icon. Unknown types still pair fine,
they just get the default icon.
"""

DEVICES: dict[str, dict[str, object]] = {
    "AB72C64C86AW2": {"name": "Echo", "generation": 1},
    "A7WXQPH584YP": {"name": "Echo", "generation": 2},
    "A3FX4UWTP28V1P": {"name": "Echo", "generation": 3},
    "A3RMGO6LYLH7YN": {"name": "Echo", "generation": 4},
    "A38EHHIB10L47V": {"name": "Echo Dot", "generation": 1},
    "AKNO1N0KSFN8L": {"name": "Echo Dot", "generation": 1},
    "A3S5BH2HU6VAYF": {"name": "Echo Dot", "generation": 2},
    "A1RABVCI4QCIKC": {"name": "Echo Dot", "generation": 3},
    "A30YDR2MK8HMRV": {"name": "Echo Dot", "generation": 3},
    "A32DOYMUN6DTXA": {"name": "Echo Dot", "generation": 3},
    "A2H4LV5GIZ1JFT": {"name": "Echo Dot", "generation": 4},
    "A2U21SRK4QGSE1": {"name": "Echo Dot", "generation": 4},
    "A2DS1Q2TPDJ48U": {"name": "Echo Dot", "generation": 5},
    "A4ZXE0RM7LQ7A": {"name": "Echo Dot", "generation": 5},
    "A2M35JJZWCQOMZ": {"name": "Echo Plus", "generation": 1},
    "A18O6U1UQFJ0XK": {"name": "Echo Plus", "generation": 2},
    "A4ZP7ZC4PI6TO": {"name": "Echo Show 5", "generation": 1},
    "A1XWJRHALS1REP": {"name": "Echo Show 5", "generation": 2},
    "A11QM4H9HGV71H": {"name": "Echo Show 5", "generation": 3},
    "A1Z88NGR2BK6A2": {"name": "Echo Show 8", "generation": 1},
    "A15996VY63BQ2D": {"name": "Echo Show 8", "generation": 2},
    "A2UONLFQW0PADH": {"name": "Echo Show 8", "generation": 3},
    "AWZZ5CVHX2CD": {"name": "Echo Show", "generation": 2},
    "AIPK7MM90V7TB": {"name": "Echo Show 10", "generation": 3},
    "ASQZWP4GPYUT7": {"name": "Echo Pop", "generation": 1},
    "A10A33FOX2NUBK": {"name": "Echo Spot", "generation": 1},
    "A3EH2E0YZ30OD6": {"name": "Echo Spot", "generation": 2},
    "A3RBAYBE7VM004": {"name": "Echo Studio", "generation": 1},
}

# Amazon Polly voices usable via SSML <voice name="..."> tags.
VOICES: list[dict[str, str]] = [
    {"id": "Zeina", "lang": "arb", "name": "Arabic - Zeina"},
    {"id": "Zhiyu", "lang": "cmn-CN", "name": "Chinese (Mandarin) - Zhiyu"},
    {"id": "Naja", "lang": "da-DK", "name": "Danish - Naja"},
    {"id": "Mads", "lang": "da-DK", "name": "Danish - Mads"},
    {"id": "Lotte", "lang": "nl-NL", "name": "Dutch - Lotte"},
    {"id": "Ruben", "lang": "nl-NL", "name": "Dutch - Ruben"},
    {"id": "Nicole", "lang": "en-AU", "name": "English (Australian) - Nicole"},
    {"id": "Russell", "lang": "en-AU", "name": "English (Australian) - Russell"},
    {"id": "Amy", "lang": "en-GB", "name": "English (British) - Amy"},
    {"id": "Emma", "lang": "en-GB", "name": "English (British) - Emma"},
    {"id": "Brian", "lang": "en-GB", "name": "English (British) - Brian"},
    {"id": "Aditi", "lang": "en-IN", "name": "English (Indian) - Aditi"},
    {"id": "Raveena", "lang": "en-IN", "name": "English (Indian) - Raveena"},
    {"id": "Ivy", "lang": "en-US", "name": "English (US) - Ivy"},
    {"id": "Joanna", "lang": "en-US", "name": "English (US) - Joanna"},
    {"id": "Kendra", "lang": "en-US", "name": "English (US) - Kendra"},
    {"id": "Kimberly", "lang": "en-US", "name": "English (US) - Kimberly"},
    {"id": "Salli", "lang": "en-US", "name": "English (US) - Salli"},
    {"id": "Joey", "lang": "en-US", "name": "English (US) - Joey"},
    {"id": "Justin", "lang": "en-US", "name": "English (US) - Justin"},
    {"id": "Kevin", "lang": "en-US", "name": "English (US) - Kevin"},
    {"id": "Matthew", "lang": "en-US", "name": "English (US) - Matthew"},
    {"id": "Geraint", "lang": "en-GB-WLS", "name": "English (Welsh) - Geraint"},
    {"id": "Celine", "lang": "fr-FR", "name": "French - Céline"},
    {"id": "Lea", "lang": "fr-FR", "name": "French - Léa"},
    {"id": "Mathieu", "lang": "fr-FR", "name": "French - Mathieu"},
    {"id": "Chantal", "lang": "fr-CA", "name": "French (Canadian) - Chantal"},
    {"id": "Marlene", "lang": "de-DE", "name": "German - Marlene"},
    {"id": "Vicki", "lang": "de-DE", "name": "German - Vicki"},
    {"id": "Hans", "lang": "de-DE", "name": "German - Hans"},
    {"id": "Dora", "lang": "is-IS", "name": "Icelandic - Dóra"},
    {"id": "Karl", "lang": "is-IS", "name": "Icelandic - Karl"},
    {"id": "Carla", "lang": "it-IT", "name": "Italian - Carla"},
    {"id": "Bianca", "lang": "it-IT", "name": "Italian - Bianca"},
    {"id": "Giorgio", "lang": "it-IT", "name": "Italian - Giorgio"},
    {"id": "Mizuki", "lang": "ja-JP", "name": "Japanese - Mizuki"},
    {"id": "Takumi", "lang": "ja-JP", "name": "Japanese - Takumi"},
    {"id": "Seoyeon", "lang": "ko-KR", "name": "Korean - Seoyeon"},
    {"id": "Liv", "lang": "nb-NO", "name": "Norwegian - Liv"},
    {"id": "Ewa", "lang": "pl-PL", "name": "Polish - Ewa"},
    {"id": "Maja", "lang": "pl-PL", "name": "Polish - Maja"},
    {"id": "Jacek", "lang": "pl-PL", "name": "Polish - Jacek"},
    {"id": "Jan", "lang": "pl-PL", "name": "Polish - Jan"},
    {"id": "Camila", "lang": "pt-BR", "name": "Portuguese (Brazilian) - Camila"},
    {"id": "Vitoria", "lang": "pt-BR", "name": "Portuguese (Brazilian) - Vitória"},
    {"id": "Ricardo", "lang": "pt-BR", "name": "Portuguese (Brazilian) - Ricardo"},
    {"id": "Ines", "lang": "pt-PT", "name": "Portuguese (European) - Inês"},
    {"id": "Cristiano", "lang": "pt-PT", "name": "Portuguese (European) - Cristiano"},
    {"id": "Carmen", "lang": "ro-RO", "name": "Romanian - Carmen"},
    {"id": "Tatyana", "lang": "ru-RU", "name": "Russian - Tatyana"},
    {"id": "Maxim", "lang": "ru-RU", "name": "Russian - Maxim"},
    {"id": "Conchita", "lang": "es-ES", "name": "Spanish (Spain) - Conchita"},
    {"id": "Lucia", "lang": "es-ES", "name": "Spanish (Spain) - Lucia"},
    {"id": "Enrique", "lang": "es-ES", "name": "Spanish (Spain) - Enrique"},
    {"id": "Mia", "lang": "es-MX", "name": "Spanish (Mexican) - Mia"},
    {"id": "Lupe", "lang": "es-US", "name": "Spanish (US) - Lupe"},
    {"id": "Penelope", "lang": "es-US", "name": "Spanish (US) - Penélope"},
    {"id": "Miguel", "lang": "es-US", "name": "Spanish (US) - Miguel"},
    {"id": "Astrid", "lang": "sv-SE", "name": "Swedish - Astrid"},
    {"id": "Filiz", "lang": "tr-TR", "name": "Turkish - Filiz"},
    {"id": "Gwyneth", "lang": "cy-GB", "name": "Welsh - Gwyneth"},
]
